package: search_it_with_gpt
version: '1.0.0'
author: 'alex+ Digitales Marketing - Alexander Walther'
supportpage: https://github.com/alexplusde/search_it_with_gpt


requires:
    php:
        version: '>8.1,<9'
    redaxo: ^5.16
    package: 
        yrewrite: '^2.10.0'
        search_it: '^6.10.0'

pages:
    search_it/with_gpt:
        title: translate:search_it_with_gpt_title
        icon: rex-icon fa-gear
        perm: search_it_with_gpt[]
        subpages:
            settings:
                title: translate:search_it_with_gpt_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:search_it_with_gpt_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                perm: search_it_with_gpt[docs]

default_config:
    token: ''

installer_ignore:
- .DS_Store
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
